import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Table } from "./components/table";
import { Candle } from "./components/candle/candle";
import { Book } from "./components/book/book";
import Image from "next/image";
import { Introducao } from "./components/introducao";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout()
{
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col overflow-auto">
        <Introducao>
          <Table>
            <div
              className="w-full h-full flex justify-between"
              style={{ padding: "100px 50px" }}
            >
              <div className="flex flex-col items-end" style={{ width: 300 }}>
                <Candle flame={1} />
                <Image width={200} height={300} src="/rose.png" style={{ transform: "rotate(-60deg)" }} />
              </div>
              
              <Book />
              <div className="flex flex-col" style={{ width: 300 }}>
                <Candle flame={2} />
                <Image width={300} height={300} src="/pen.png"/>
              </div>
            </div>
          </Table>
        </Introducao>
      </body>
    </html>
  );
}
